//go:build !ignore_autogenerated

/*
Copyright 2023 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightningConfig) DeepCopyInto(out *LightningConfig) {
	*out = *in
	if in.DisableBoltcard != nil {
		in, out := &in.DisableBoltcard, &out.DisableBoltcard
		*out = new(bool)
		**out = **in
	}
	if in.InternalNodeRef != nil {
		in, out := &in.InternalNodeRef, &out.InternalNodeRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightningConfig.
func (in *LightningConfig) DeepCopy() *LightningConfig {
	if in == nil {
		return nil
	}
	out := new(LightningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnChainConfig) DeepCopyInto(out *OnChainConfig) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.AccountKeyPath != nil {
		in, out := &in.AccountKeyPath, &out.AccountKeyPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnChainConfig.
func (in *OnChainConfig) DeepCopy() *OnChainConfig {
	if in == nil {
		return nil
	}
	out := new(OnChainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethod) DeepCopyInto(out *PaymentMethod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethod.
func (in *PaymentMethod) DeepCopy() *PaymentMethod {
	if in == nil {
		return nil
	}
	out := new(PaymentMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaymentMethod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodList) DeepCopyInto(out *PaymentMethodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PaymentMethod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodList.
func (in *PaymentMethodList) DeepCopy() *PaymentMethodList {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PaymentMethodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodObservation) DeepCopyInto(out *PaymentMethodObservation) {
	*out = *in
	if in.WalletBalance != nil {
		in, out := &in.WalletBalance, &out.WalletBalance
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastSyncAt != nil {
		in, out := &in.LastSyncAt, &out.LastSyncAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodObservation.
func (in *PaymentMethodObservation) DeepCopy() *PaymentMethodObservation {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodParameters) DeepCopyInto(out *PaymentMethodParameters) {
	*out = *in
	in.StoreRef.DeepCopyInto(&out.StoreRef)
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OnChain != nil {
		in, out := &in.OnChain, &out.OnChain
		*out = new(OnChainConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Lightning != nil {
		in, out := &in.Lightning, &out.Lightning
		*out = new(LightningConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodParameters.
func (in *PaymentMethodParameters) DeepCopy() *PaymentMethodParameters {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodSpec) DeepCopyInto(out *PaymentMethodSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodSpec.
func (in *PaymentMethodSpec) DeepCopy() *PaymentMethodSpec {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodStatus) DeepCopyInto(out *PaymentMethodStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodStatus.
func (in *PaymentMethodStatus) DeepCopy() *PaymentMethodStatus {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreReference) DeepCopyInto(out *StoreReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreReference.
func (in *StoreReference) DeepCopy() *StoreReference {
	if in == nil {
		return nil
	}
	out := new(StoreReference)
	in.DeepCopyInto(out)
	return out
}
