//go:build !ignore_autogenerated

/*
Copyright 2023 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckoutSettings) DeepCopyInto(out *CheckoutSettings) {
	*out = *in
	if in.SpeedPolicy != nil {
		in, out := &in.SpeedPolicy, &out.SpeedPolicy
		*out = new(string)
		**out = **in
	}
	if in.PaymentMethods != nil {
		in, out := &in.PaymentMethods, &out.PaymentMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultPaymentMethod != nil {
		in, out := &in.DefaultPaymentMethod, &out.DefaultPaymentMethod
		*out = new(string)
		**out = **in
	}
	if in.ExpirationMinutes != nil {
		in, out := &in.ExpirationMinutes, &out.ExpirationMinutes
		*out = new(int32)
		**out = **in
	}
	if in.MonitoringExpiration != nil {
		in, out := &in.MonitoringExpiration, &out.MonitoringExpiration
		*out = new(int32)
		**out = **in
	}
	if in.PaymentTolerance != nil {
		in, out := &in.PaymentTolerance, &out.PaymentTolerance
		*out = new(float64)
		**out = **in
	}
	if in.RedirectAutomatically != nil {
		in, out := &in.RedirectAutomatically, &out.RedirectAutomatically
		*out = new(bool)
		**out = **in
	}
	if in.RequiresRefundEmail != nil {
		in, out := &in.RequiresRefundEmail, &out.RequiresRefundEmail
		*out = new(bool)
		**out = **in
	}
	if in.CheckoutType != nil {
		in, out := &in.CheckoutType, &out.CheckoutType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckoutSettings.
func (in *CheckoutSettings) DeepCopy() *CheckoutSettings {
	if in == nil {
		return nil
	}
	out := new(CheckoutSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Invoice) DeepCopyInto(out *Invoice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Invoice.
func (in *Invoice) DeepCopy() *Invoice {
	if in == nil {
		return nil
	}
	out := new(Invoice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Invoice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceList) DeepCopyInto(out *InvoiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Invoice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceList.
func (in *InvoiceList) DeepCopy() *InvoiceList {
	if in == nil {
		return nil
	}
	out := new(InvoiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvoiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceObservation) DeepCopyInto(out *InvoiceObservation) {
	*out = *in
	if in.MonitoringExpiration != nil {
		in, out := &in.MonitoringExpiration, &out.MonitoringExpiration
		*out = (*in).DeepCopy()
	}
	if in.ExpirationTime != nil {
		in, out := &in.ExpirationTime, &out.ExpirationTime
		*out = (*in).DeepCopy()
	}
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.AvailableStatusesForManualMarking != nil {
		in, out := &in.AvailableStatusesForManualMarking, &out.AvailableStatusesForManualMarking
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PaymentMethods != nil {
		in, out := &in.PaymentMethods, &out.PaymentMethods
		*out = make([]PaymentMethodDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceObservation.
func (in *InvoiceObservation) DeepCopy() *InvoiceObservation {
	if in == nil {
		return nil
	}
	out := new(InvoiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceParameters) DeepCopyInto(out *InvoiceParameters) {
	*out = *in
	out.StoreRef = in.StoreRef
	if in.OrderID != nil {
		in, out := &in.OrderID, &out.OrderID
		*out = new(string)
		**out = **in
	}
	if in.NotificationURL != nil {
		in, out := &in.NotificationURL, &out.NotificationURL
		*out = new(string)
		**out = **in
	}
	if in.RedirectURL != nil {
		in, out := &in.RedirectURL, &out.RedirectURL
		*out = new(string)
		**out = **in
	}
	if in.NotificationEmail != nil {
		in, out := &in.NotificationEmail, &out.NotificationEmail
		*out = new(string)
		**out = **in
	}
	if in.ItemDesc != nil {
		in, out := &in.ItemDesc, &out.ItemDesc
		*out = new(string)
		**out = **in
	}
	if in.ItemCode != nil {
		in, out := &in.ItemCode, &out.ItemCode
		*out = new(string)
		**out = **in
	}
	if in.Physical != nil {
		in, out := &in.Physical, &out.Physical
		*out = new(bool)
		**out = **in
	}
	if in.TaxIncluded != nil {
		in, out := &in.TaxIncluded, &out.TaxIncluded
		*out = new(bool)
		**out = **in
	}
	if in.BuyerName != nil {
		in, out := &in.BuyerName, &out.BuyerName
		*out = new(string)
		**out = **in
	}
	if in.BuyerEmail != nil {
		in, out := &in.BuyerEmail, &out.BuyerEmail
		*out = new(string)
		**out = **in
	}
	if in.BuyerCountry != nil {
		in, out := &in.BuyerCountry, &out.BuyerCountry
		*out = new(string)
		**out = **in
	}
	if in.BuyerZip != nil {
		in, out := &in.BuyerZip, &out.BuyerZip
		*out = new(string)
		**out = **in
	}
	if in.BuyerState != nil {
		in, out := &in.BuyerState, &out.BuyerState
		*out = new(string)
		**out = **in
	}
	if in.BuyerCity != nil {
		in, out := &in.BuyerCity, &out.BuyerCity
		*out = new(string)
		**out = **in
	}
	if in.BuyerAddress1 != nil {
		in, out := &in.BuyerAddress1, &out.BuyerAddress1
		*out = new(string)
		**out = **in
	}
	if in.BuyerAddress2 != nil {
		in, out := &in.BuyerAddress2, &out.BuyerAddress2
		*out = new(string)
		**out = **in
	}
	if in.BuyerPhone != nil {
		in, out := &in.BuyerPhone, &out.BuyerPhone
		*out = new(string)
		**out = **in
	}
	if in.ExtendedNotifications != nil {
		in, out := &in.ExtendedNotifications, &out.ExtendedNotifications
		*out = new(bool)
		**out = **in
	}
	if in.FullNotifications != nil {
		in, out := &in.FullNotifications, &out.FullNotifications
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CheckoutQueryString != nil {
		in, out := &in.CheckoutQueryString, &out.CheckoutQueryString
		*out = new(string)
		**out = **in
	}
	if in.Receipt != nil {
		in, out := &in.Receipt, &out.Receipt
		*out = new(InvoiceReceiptSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceParameters.
func (in *InvoiceParameters) DeepCopy() *InvoiceParameters {
	if in == nil {
		return nil
	}
	out := new(InvoiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceReceiptSettings) DeepCopyInto(out *InvoiceReceiptSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ShowQR != nil {
		in, out := &in.ShowQR, &out.ShowQR
		*out = new(bool)
		**out = **in
	}
	if in.ShowPayments != nil {
		in, out := &in.ShowPayments, &out.ShowPayments
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceReceiptSettings.
func (in *InvoiceReceiptSettings) DeepCopy() *InvoiceReceiptSettings {
	if in == nil {
		return nil
	}
	out := new(InvoiceReceiptSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceSpec) DeepCopyInto(out *InvoiceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceSpec.
func (in *InvoiceSpec) DeepCopy() *InvoiceSpec {
	if in == nil {
		return nil
	}
	out := new(InvoiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceStatus) DeepCopyInto(out *InvoiceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceStatus.
func (in *InvoiceStatus) DeepCopy() *InvoiceStatus {
	if in == nil {
		return nil
	}
	out := new(InvoiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentDetails) DeepCopyInto(out *PaymentDetails) {
	*out = *in
	if in.ReceivedDate != nil {
		in, out := &in.ReceivedDate, &out.ReceivedDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentDetails.
func (in *PaymentDetails) DeepCopy() *PaymentDetails {
	if in == nil {
		return nil
	}
	out := new(PaymentDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodDetails) DeepCopyInto(out *PaymentMethodDetails) {
	*out = *in
	if in.Payments != nil {
		in, out := &in.Payments, &out.Payments
		*out = make([]PaymentDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodDetails.
func (in *PaymentMethodDetails) DeepCopy() *PaymentMethodDetails {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptSettings) DeepCopyInto(out *ReceiptSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ShowQR != nil {
		in, out := &in.ShowQR, &out.ShowQR
		*out = new(bool)
		**out = **in
	}
	if in.ShowPayments != nil {
		in, out := &in.ShowPayments, &out.ShowPayments
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptSettings.
func (in *ReceiptSettings) DeepCopy() *ReceiptSettings {
	if in == nil {
		return nil
	}
	out := new(ReceiptSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreReference) DeepCopyInto(out *StoreReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreReference.
func (in *StoreReference) DeepCopy() *StoreReference {
	if in == nil {
		return nil
	}
	out := new(StoreReference)
	in.DeepCopyInto(out)
	return out
}
